### ISSUE TITLE
phpStorm -> generateSenchaTouch2Project.sh

### ISSUE THREAD

**Issue by jk171505** [davidtucker/ST2PowerTools#3]
For some reason, in phpStorm (Tools -> Run command -> generateSenchaTouch2Project.sh)  I get the message:

> generateSenchaTouch2Project.sh
> Cannot run program "generateSenchaTouch2Project.sh" (in directory "/Projects/SenchaTouch2/projects/SampleApp"): error=2, No such file or directory

but I am able to generate the template in command line using terminal, from the same directory.

Any ideas what can be a reason?

**Comment by jk171505** [comment]
Ok, the problem seems to be with the path to generateSenchaTouch2Project.sh.
I did everything as described  in the "Getting Setup For Sencha Touch 2 Development on Your Mac" tutorial.
The "generateSenchaTouch2Project.sh" is accessible in terminal, but for some reason it is not in the command line in phpStorm.

The script can be run using the path: ' /usr/local/bin/generateSenchaTouch2Project.sh'. It is accessible from terminal from any location, but phpStorm cannot access it without direct path.

**Comment by andreasciamanna** [comment]
I'm facing the same issue: did you solve otherwise?

**Comment by matullaa** [comment]
well i think i have the way.....
Mac is my friend don't try on my windows PC yet
Following PHPStorm Guidelines just go to menu : PHPStorm->Preferences->Command line tool Support
On the right window click on + to add a new command line
Choose Custom Framework in dropdown list
I set these value
Framework = ST2Tool
Tool Path = /opt/local/bin/generateSenchaTouch2Project.sh (as mentionned in README)
Alias = generateSenchaTouch2Project
Description = So Nice Tool

then apply change and try it.....it should work.
